---
title: "Exercise_8"
output: html_document
---

```{r Question 1 Installing Packages}

if (!require('devtools')){
  install.packages("devtools")
  require(devtools)
  install_version("rtimes", version = "0.5.0", repos = "http://cran.us.r-project.org") 
  library(rtimes)
}

```

```{r Question 1 }

# key removed before publishing 

API_key <- "" 
term <- "climate change"
end_date <- "20201105"
begin_date <- "20171105"
article_search_climate_change <- as_search(q=term,begin_date=begin_date,end_date=end_date,key=API_key)

# Checking the names 
names(article_search_climate_change)
# Checking Meta 
article_search_climate_change$meta
# Checking Copyright 
article_search_climate_change$copyright

# Viewing the data set
View(article_search_climate_change[3]$data)

# Finding out the number of pages as there are 10 results per page 
max_page_numder <- round((article_search_climate_change$meta$hits[1]/ 10)-1)

for (i in 1:max_page_numder) {
  article_search_climate_change <- as_search(q=term,begin_date=begin_date,end_date=end_date,key=API_key, page = i)
  print(article_search_climate_change[3]$data) 
}
# Received an Error as there was too many requests when attempting to print the articles regarding climate change over the last 3 years
```


```{r Question 2 Setting Up Packages}

if (!require('twitteR')) {
  install.packages("twitteR") 
  install.packages("tidytext") 
  install.packages("httr") 
  install.packages("rtweet")
  install.packages("httpuv") 
  install.packages("openssl") 
  remotes::install_github("ropensci/rtweet")
  
  library(twitteR) 
  library(tidytext) 
  library(httr) 
  library(rtweet) library(httpuv) 
  library(openssl)
} 

```
 
```{r Question 2}

# keys removed before publishing

Twitter_API_key <- ""
Twitter_Secret_API_key <- ""
Twitter_Access_Token <- "" 
Twitter_Access_Secret <- ""

appname <- "Earth Count"

Twitter_Token <- create_token(
  app = appname,
  consumer_key = Twitter_API_key, 
  consumer_secret = Twitter_Secret_API_key, 
  access_token = Twitter_Access_Token, 
  access_secret = Twitter_Access_Secret
)
rstats_tweets <- search_tweets(q = "#earthhour", n = 500) View(rstats_tweets)
Twitter_App <- oauth_app("Earth Count",Twitter_API_key,Twitter_Secret_API_key)

```







